branches:
    only:
        - master
        - testBranch

language: node_js
node_js:
    - "0.11"
    - "0.10"
services:
    - mongodb
before_script:
    - npm run build
script:
    - npm run test-mocha