branches:
    only:
        - master
        - testBranch

language: node_js
node_js:
    - "stable"
services:
    - mongodb
before_script:
    - npm run build
script:
    - npm run test-mocha
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8